# Makefiles are special scripts used by the gnu 'make' build automation tool to define how programs are compiled and built.
# They specify rules, dependencies, and commands for building and managing projects, 
# making it easier to automate repetitive tasks like compiling code, running tests, or cleaning up files. 

# Before you run a makefile, you need to install 'make'.

# In this makefile you need to..

# 1. Tell iVerilog to simulate the design using the testbench

# 2. Tell VVP to open the output vvp file

# Then...

# 3. Run the make command in the terminal from the test directory to run the script

# 4. Click on the .VCD file and verify the output is what you expected,
# tweak your design till it works!